version: '3.4'
services:
  db:
    image: zheiran3/mysql-springtutorial
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-mysql
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: SpringTutorial
    ports:
      - "3308:3306"
    networks:
      - udemy-network
  rest-with-spring-boot-udemy:
    image: zheiran3/springtutorial
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-spring
    working_dir: /SpringRestTutorial
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ~/Documentos/temp/SpringRestTutorial:/SpringRestTutorial
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - udemy-network
networks:
    udemy-network:
        driver: bridge